-- ════════════════════════════════════════════════════════════
-- Backfill: szacowane kcal na porcję (276 dań)
-- + szacowany czas przyrządzania (79 dań, TYLKO brakujące)
-- Wygenerowane automatycznie z eksportu tabeli dania.
-- Uruchom w Supabase SQL Editor. Wymaga wcześniejszej migracji: kolumna dania.kcal.
-- ════════════════════════════════════════════════════════════

-- 1) Kalorie na 1 porcję — nadpisuje tylko puste (świeżo dodana kolumna).
update dania d set kcal = v.kcal
from (values
  ('Bagietka', 160),
  ('Bagietka z masłem czosnkowym', 670),
  ('Bakłażan w panko', 700),
  ('Banany smażone z miodem i cynamonem', 340),
  ('Banany w cieście naleśnikowym', 520),
  ('Barszcz czerwony', 150),
  ('Batat pieczony', 110),
  ('Bigos', 560),
  ('Bitki wołowe w sosie własnym', 300),
  ('Breakfast Burrito', 800),
  ('Brownie czekoladowe', 480),
  ('Brownie z patelni', 650),
  ('Bruschetta z pomidorami i bazylią', 470),
  ('Budyń czekoladowy', 410),
  ('Budyń waniliowy z owocami', 380),
  ('Bułeczki jak z Maka', 350),
  ('Bułka', 160),
  ('Bułka grahamka', 150),
  ('Buraczki', 40),
  ('Burger wołowy', 480),
  ('Burrito z mieloną wołowiną', 610),
  ('Butter Chicken', 700),
  ('Camembert pieczony z żurawiną', 550),
  ('Carpaccio z buraka na grzankach', 590),
  ('Cebulowa (po francusku)', 450),
  ('Chia pudding z mango', 660),
  ('Chilli con carne', 860),
  ('Chipsy z jarmużu', 150),
  ('Chipsy z tortilli z dipem jogurtowym', 600),
  ('Chleb', 150),
  ('Chleb w jajku', 350),
  ('Chleb w jajku z serem', 430),
  ('Chłodnik litewski', 370),
  ('Chrupiąca ciecierzyca z piekarnika', 240),
  ('Chrupiące kąski z kurczaka', 600),
  ('Ciasto francuskie z jabłkiem i cynamonem', 640),
  ('Ciasto marchewkowe', 520),
  ('Colesław', 100),
  ('Croque Monsieur/Madame', 750),
  ('Cukinia w panierce', 420),
  ('Daktyle z masłem orzechowym', 460),
  ('Deser z mascarpone, herbatnikami i owocami', 600),
  ('Deska serów i wędlin', 650),
  ('Domowe hot dogi z prażoną cebulką', 640),
  ('Dorsz panierowany', 450),
  ('Dorsz z piekarnika', 280),
  ('Fasolka po bretońsku', 950),
  ('Faszerowana pierś kurczaka', 320),
  ('Flaki', 300),
  ('Frytki', 300),
  ('Frytki z batatów', 320),
  ('Galaretka z owocami', 220),
  ('Gazpacho', 230),
  ('Gnocchi z masłem, czosnkiem i parmezanem', 740),
  ('Gofrowe kąski', 530),
  ('Gofry z owocami i bitą śmietaną', 620),
  ('Grochówka', 550),
  ('Grzanki czosnkowe z serem', 650),
  ('Grzanki z awokado, jajkiem i pomidorem', 450),
  ('Guacamole', 290),
  ('Gulasz domowy (sos mięsny)', 480),
  ('Gulaszowa', 500),
  ('Gyros domowy z sosem czosnkowym', 480),
  ('Huevos Rancheros', 700),
  ('Jabłka pieczone z cynamonem', 290),
  ('Jabłka w cieście', 700),
  ('Jabłka w cieście naleśnikowym', 540),
  ('Jajecznica', 340),
  ('Jajecznica z boczkiem i szczypiorkiem', 530),
  ('Jajka faszerowane', 260),
  ('Jajka na miękko', 150),
  ('Jajka na twardo z majonezem', 250),
  ('Jajka po turecku*', 590),
  ('Jajka sadzone z boczkiem', 450),
  ('Jajka sadzone z ziemniakami z patelni i mizerią', 690),
  ('Jajka w majonezie ze szczypiorkiem', 360),
  ('Jajka z papryką ', 350),
  ('Jarzynowa', 260),
  ('Jogurt grecki z miodem i orzechami', 580),
  ('Kalafiorowa', 370),
  ('Kanapki jak ze szkoły', 460),
  ('Kanapki na ciepło z mozzarellą, pomidorem i szynką', 470),
  ('Kanapki z jajkiem', 480),
  ('Kanapki z łososiem i twarożkiem', 370),
  ('Kanapki z serem i wędliną', 430),
  ('Kanapki z twarogiem i miodem', 440),
  ('Kapsalon', 410),
  ('Kapuśniak', 420),
  ('Kasza bulgur', 280),
  ('Kasza bulgur z kurczakiem, papryką i sosem jogurtowym', 620),
  ('Kasza gryczana', 280),
  ('Kasza jaglana', 280),
  ('Kasza jęczmienna', 280),
  ('Kasza manna z sokiem malinowym', 360),
  ('Kisiel owocowy', 260),
  ('Kluski z serem i skwarkami', 540),
  ('Koktajl bananowo-truskawkowy', 380),
  ('Koktajl owocowy z jogurtem', 370),
  ('Kopytka z cebulką', 700),
  ('Koreczki', 250),
  ('Kotlet schabowy', 500),
  ('Kotlety mielone', 550),
  ('Krakersy z serkiem i ogórkiem', 210),
  ('Krążki cebulowe', 580),
  ('Krem budyniowy z bananami', 460),
  ('Krem z mascarpone i kajmaku', 550),
  ('Krokiety z kapustą kiszoną i grzybami', 450),
  ('Krupnik', 480),
  ('Kulki kokosowe', 400),
  ('Kulki mocy z płatków owsianych', 480),
  ('Kulki owsiane z masłem orzechowym i miodem', 360),
  ('Kulki serowe w panierce', 700),
  ('Kurczak curry z ryżem', 740),
  ('Kurczak po chińsku', 380),
  ('Kurczak w panko', 650),
  ('Kuskus', 300),
  ('Kuskus z kurczakiem i warzywami', 700),
  ('Lasagne Bolognese', 750),
  ('Leczo', 250),
  ('Lody domowe waniliowe', 490),
  ('Lody z jogurtu i owoców', 340),
  ('Makaron penne', 360),
  ('Makaron spaghetti', 360),
  ('Makaron świderki', 360),
  ('Makaron z kiełbasą, cebulą i passatą', 900),
  ('Makaron z kiełbaską i sosem pieczarkowym', 780),
  ('Makaron z kurczakiem w sosie pomidorowym', 490),
  ('Makaron z kurczakiem, brokułem i sosem śmietanowym', 850),
  ('Makaron z pesto i oliwkami', 570),
  ('Makaron z pesto, kurczakiem i pomidorkami', 800),
  ('Makaron z pomidorami, czosnkiem i parmezanem', 680),
  ('Makaron z serem, boczkiem i cebulką', 800),
  ('Makaron z warzywami w sosie serowym', 470),
  ('Makowiec rolowany', 450),
  ('Marry me chicken gnocchi', 520),
  ('Migdały prażone z papryką', 670),
  ('Mini burgery', 800),
  ('Mini hot dogi', 550),
  ('Mini muffinki bananowe', 460),
  ('Mini muffinki wytrawne', 620),
  ('Mini pancakes z owocami', 550),
  ('Mini rogaliki z ciasta francuskiego i czekolady', 540),
  ('Mini szaszłyki z kurczaka', 260),
  ('Mini tortille', 470),
  ('Mini zapiekanki z pieczarkami', 590),
  ('Mizeria', 70),
  ('Mozzarella sticks', 600),
  ('Mug cake czekoladowy z mikrofali', 690),
  ('Mus czekoladowy z banana i kakao', 170),
  ('Nachosy z sosem serowym', 700),
  ('Naleśniki crêpes Suzette (pomarańczowe)*', 760),
  ('Naleśniki wytrawne z serem i szynką', 750),
  ('Naleśniki z boczkiem', 750),
  ('Naleśniki z dżemem', 580),
  ('Naleśniki z dżemem i bitą śmietaną', 650),
  ('Nuggetsy domowe', 550),
  ('Ogórkowa', 400),
  ('Omlet', 350),
  ('Omlet z serem, szynką i warzywami', 490),
  ('Orzeszki w miodzie i chili', 640),
  ('Owocowa sałatka z miętą', 210),
  ('Owsianka', 540),
  ('Owsianka kakaowa z bananem', 500),
  ('Owsianka nocna', 450),
  ('Paluszki z ciasta francuskiego z szynką', 620),
  ('Panierowana pierś kurczaka', 400),
  ('Panini z kurczakiem, serem i sosem BBQ', 720),
  ('Panna cotta z owocami', 610),
  ('Parówki', 500),
  ('Parówki w cieście francuskim', 660),
  ('Pasta jajeczna', 340),
  ('Pasta jajeczna na krakersach', 330),
  ('Pasta z awokado i jajka', 310),
  ('Pasta z makreli wędzonej', 530),
  ('Pieczarkowa', 380),
  ('Pieczona owsianka', 650),
  ('Pieczone pieczarki z serem', 320),
  ('Pieczone udka kurczaka', 350),
  ('Pieczone ziemniaczki z dipem', 630),
  ('Pierogi ruskie', 640),
  ('Pierogi z mięsem', 640),
  ('Pizza domowa', 760),
  ('Pizza na tortilli', 540),
  ('Pizzerinki', 700),
  ('Placki bananowe z „chrupką”', 590),
  ('Placki bananowe z jogurtem i owocami', 550),
  ('Placki ziemniaczane mini', 380),
  ('Placki ziemniaczane z sosem czosnkowym', 730),
  ('Placki ziemniaczane ze śmietaną', 460),
  ('Placuszki twarogowe', 530),
  ('Płatki z mlekiem', 310),
  ('Polędwiczka wieprzowa z kurkami', 440),
  ('Pomidorówka', 380),
  ('Popcorn karmelowy', 730),
  ('Prażona kukurydza z masłem', 420),
  ('Pstrąg pieczony z masłem czosnkowym', 400),
  ('Pulpety w sosie koperkowym', 450),
  ('Puree ziemniaczane', 200),
  ('Pyzy/kluski śląskie', 560),
  ('Quesadilla z serem i fasolą', 900),
  ('Quesadilla z serem i kurczakiem', 750),
  ('Quesadilla z serem, kurczakiem i papryką', 790),
  ('Quesadilla z szarpaną wieprzowiną', 710),
  ('Quinoa', 300),
  ('Racuchy jabłkowe mini', 570),
  ('Racuchy z jabłkami', 650),
  ('Risotto z warzywami', 350),
  ('Roladki z cukinii z serkiem', 330),
  ('Roladki z szynki i serka', 280),
  ('Rosół', 430),
  ('Ryba po grecku', 350),
  ('Ryż biały', 350),
  ('Ryż brązowy', 350),
  ('Ryż na mleku z cynamonem i jabłkiem', 490),
  ('Ryż smażony z jajkiem, kurczakiem i warzywami', 620),
  ('Ryż z warzywami stir-fry', 520),
  ('Sałatka caprese', 530),
  ('Sałatka caprese w kubeczku', 280),
  ('Sałatka cezar z kurczakiem', 620),
  ('Sałatka grecka z fetą', 510),
  ('Sałatka gyros', 500),
  ('Sałatka makaronowa z kurczakiem i kukurydzą', 730),
  ('Sałatka z jajkiem, bekonem i grzankami', 740),
  ('Sałatka z kurczakiem, fetą i grzankami', 640),
  ('Sałatka z tuńczykiem i jajkiem', 370),
  ('Sałatka zielona', 30),
  ('Ser halloumi z patelni', 430),
  ('Serek waniliowy z owocami i granolą', 480),
  ('Serniczek na zimno w pucharku', 600),
  ('Sernik na zimno', 550),
  ('Shakshuka z jajkami i pomidorami', 470),
  ('Skrzydełka BBQ', 620),
  ('Słupki warzywne z hummusem', 330),
  ('Smoothie bowl z owocami i granolą', 550),
  ('Sorbet truskawkowy', 270),
  ('Spaghetti Aglio e Olio', 380),
  ('Spaghetti bolognese', 600),
  ('Spaghetti carbonara', 450),
  ('Spring rolls (sajgonki)', 340),
  ('Stek wołowy', 520),
  ('Stek z kalafiora', 200),
  ('Stir-fry z wołowiną', 350),
  ('Surówka z kapusty', 30),
  ('Surówka z kiszonej kapusty', 60),
  ('Surówka z marchewki', 40),
  ('Sushi bez zawijania', 450),
  ('Szarlotka', 550),
  ('Szybkie leczo z kiełbasą i papryką', 650),
  ('Tacos z mięsem mielonym i warzywami', 850),
  ('Tagliatelle z boczniakami', 450),
  ('Tagliatelle z polędwicą wołową', 550),
  ('Tarta warzywna', 880),
  ('Tiramisu', 600),
  ('Tortilla kebab', 600),
  ('Tortilla pizza z serem, salami i pieczarkami', 560),
  ('Tortilla z kurczakiem, warzywami i sosem czosnkowym', 660),
  ('Tortilla z serem, jajkiem i szynką', 390),
  ('Tosty francuskie na słodko', 460),
  ('Tosty francuskie na słono', 470),
  ('Tosty francuskie na słono z serem i szynką', 500),
  ('Tosty z serem i szynką', 530),
  ('Tosty z serem, szynką i ogórkiem kiszonym', 380),
  ('Twarożek', 270),
  ('Wrap z jajkiem, bekonem i sałatą', 660),
  ('Wrap z kurczakiem i warzywami', 580),
  ('Wrap z mięsem mielonym, serem i warzywami', 900),
  ('Zapiekane bagietki z serem, pieczarkami i szynką', 700),
  ('Zapiekanki', 600),
  ('Ziemniaki gotowane', 150),
  ('Ziemniaki pieczone', 170),
  ('Zupa krem z batatów', 600),
  ('Zupa krem z brokułem i cukinią', 330),
  ('Zupa krem z pomidorów z grzankami', 430),
  ('Zupa miso z tofu', 170),
  ('Żeberka pieczone w miodzie i musztardzie', 660),
  ('Żur', 450)
) as v(nazwa, kcal)
where d."Danie" = v.nazwa and d.kcal is null;

-- 2) Czas przyrządzania — TYLKO tam gdzie brak (ręcznie wpisanych nie ruszamy).
update dania d set czas_minuty = v.czas
from (values
  ('Bagietka', 5),
  ('Batat pieczony', 45),
  ('Bigos', 180),
  ('Bitki wołowe w sosie własnym', 90),
  ('Bułeczki jak z Maka', 10),
  ('Bułka', 5),
  ('Bułka grahamka', 5),
  ('Buraczki', 60),
  ('Burger wołowy', 30),
  ('Burrito z mieloną wołowiną', 40),
  ('Chilli con carne', 60),
  ('Chleb', 5),
  ('Colesław', 15),
  ('Dorsz panierowany', 35),
  ('Dorsz z piekarnika', 35),
  ('Fasolka po bretońsku', 120),
  ('Faszerowana pierś kurczaka', 45),
  ('Frytki', 30),
  ('Gulasz domowy (sos mięsny)', 120),
  ('Gyros domowy z sosem czosnkowym', 60),
  ('Jajka z papryką ', 15),
  ('Kapsalon', 45),
  ('Kasza bulgur', 20),
  ('Kasza gryczana', 20),
  ('Kasza jaglana', 20),
  ('Kasza jęczmienna', 20),
  ('Kluski z serem i skwarkami', 25),
  ('Kopytka z cebulką', 60),
  ('Kotlet schabowy', 45),
  ('Kotlety mielone', 40),
  ('Krokiety z kapustą kiszoną i grzybami', 90),
  ('Kurczak po chińsku', 50),
  ('Kuskus', 10),
  ('Lasagne Bolognese', 90),
  ('Leczo', 40),
  ('Makaron penne', 15),
  ('Makaron spaghetti', 15),
  ('Makaron świderki', 15),
  ('Makaron z kiełbaską i sosem pieczarkowym', 25),
  ('Makaron z kurczakiem w sosie pomidorowym', 30),
  ('Makaron z pesto i oliwkami', 20),
  ('Makaron z warzywami w sosie serowym', 30),
  ('Marry me chicken gnocchi', 40),
  ('Mizeria', 15),
  ('Panierowana pierś kurczaka', 40),
  ('Pieczone udka kurczaka', 70),
  ('Pierogi ruskie', 90),
  ('Pierogi z mięsem', 120),
  ('Pizza domowa', 120),
  ('Placki ziemniaczane ze śmietaną', 45),
  ('Polędwiczka wieprzowa z kurkami', 50),
  ('Pstrąg pieczony z masłem czosnkowym', 40),
  ('Pulpety w sosie koperkowym', 60),
  ('Puree ziemniaczane', 25),
  ('Pyzy/kluski śląskie', 90),
  ('Quesadilla z szarpaną wieprzowiną', 180),
  ('Quinoa', 20),
  ('Risotto z warzywami', 40),
  ('Ryba po grecku', 60),
  ('Ryż biały', 20),
  ('Ryż brązowy', 35),
  ('Sałatka zielona', 10),
  ('Spaghetti Aglio e Olio', 20),
  ('Spaghetti bolognese', 90),
  ('Spaghetti carbonara', 30),
  ('Stek wołowy', 25),
  ('Stek z kalafiora', 35),
  ('Stir-fry z wołowiną', 40),
  ('Surówka z kapusty', 15),
  ('Surówka z kiszonej kapusty', 15),
  ('Surówka z marchewki', 10),
  ('Sushi bez zawijania', 40),
  ('Tagliatelle z boczniakami', 30),
  ('Tagliatelle z polędwicą wołową', 35),
  ('Tortilla kebab', 30),
  ('Zapiekanki', 30),
  ('Ziemniaki gotowane', 25),
  ('Ziemniaki pieczone', 50),
  ('Żeberka pieczone w miodzie i musztardzie', 120)
) as v(nazwa, czas)
where d."Danie" = v.nazwa and d.czas_minuty is null;

-- 3) Kontrola: ile dań nadal bez kcal / bez czasu (powinno być 0 albo prawie 0).
select
  count(distinct "Danie") filter (where kcal is null) as dania_bez_kcal,
  count(distinct "Danie") filter (where czas_minuty is null) as dania_bez_czasu
from dania;
