-- ════════════════════════════════════════════════════════════
-- Backfill: kcal_100g składników (auto-liczenie kalorii dań)
-- 144 aktualizacji istniejących wpisów skladniki_meta
-- + 271 nowych wpisów (składniki bez meta)
-- Wymaga migracji: kolumna skladniki_meta.kcal_100g.
-- ════════════════════════════════════════════════════════════

-- 1) Kalorie dla istniejących wpisów (tylko puste — ręcznych nie ruszamy).
update skladniki_meta m set kcal_100g = v.kcal
from (values
  ('bazylia', 25),
  ('boczek', 500),
  ('boczek wedzony', 500),
  ('boczniaki', 35),
  ('brokul', 34),
  ('bulion', 250),
  ('bulka tarta', 380),
  ('bulki do burgerow', 290),
  ('buraki', 45),
  ('cebula', 40),
  ('cebula czerwona', 40),
  ('chilli', 300),
  ('chleb', 250),
  ('chleb tostowy', 270),
  ('cukier', 400),
  ('cukinia', 20),
  ('cytryna', 30),
  ('czosnek', 145),
  ('dorsz', 80),
  ('drozdze suche', 350),
  ('fasola biala', 330),
  ('fasola w puszce', 100),
  ('filet z dorsza', 80),
  ('filet z lososia', 200),
  ('frytki', 300),
  ('galka muszkatolowa', 525),
  ('garam masala', 320),
  ('gnocchi', 160),
  ('grzyby suszone', 280),
  ('imbir', 80),
  ('jablko', 50),
  ('jajko', 143),
  ('jogurt naturalny', 65),
  ('kalafior', 25),
  ('kapusta biala', 30),
  ('kapusta czerwona', 30),
  ('kapusta kiszona', 20),
  ('kapusta pekinska', 15),
  ('karczek wolowy', 200),
  ('kasza bulgur', 340),
  ('kasza gryczana', 340),
  ('kasza jaglana', 350),
  ('kasza jeczmienna', 340),
  ('ketchup', 100),
  ('kielbasa slaska', 300),
  ('kmin rzymski', 375),
  ('koncentrat pomidorowy', 90),
  ('kukurydza w puszce', 90),
  ('kumin', 375),
  ('kurki', 30),
  ('kuskus', 350),
  ('lisc laurowy', 310),
  ('lopatka wieprzowa', 250),
  ('majeranek', 270),
  ('majonez', 700),
  ('maka', 360),
  ('maka 00', 360),
  ('maka ziemniaczana', 340),
  ('makaron', 360),
  ('makaron lasagne', 360),
  ('makaron muszelki', 360),
  ('makaron penne', 360),
  ('makaron spaghetti', 360),
  ('makaron swiderki', 360),
  ('makaron tagliatelle', 360),
  ('mango', 60),
  ('marchewka', 35),
  ('maslo', 735),
  ('miod', 320),
  ('mleko', 55),
  ('mozarella', 280),
  ('musztarda', 130),
  ('natka pietruszki', 40),
  ('nori', 350),
  ('ocet', 20),
  ('ocet ryzowy', 20),
  ('ogorek', 15),
  ('ogorek kiszony', 12),
  ('olej', 884),
  ('oliwa', 884),
  ('oliwki czarne', 150),
  ('oliwki zielone', 150),
  ('oregano', 270),
  ('panko', 370),
  ('papryka czerwona', 30),
  ('papryka ostra', 290),
  ('papryka slodka', 290),
  ('papryka wedzona', 290),
  ('papryka zolta', 30),
  ('parmezan', 400),
  ('pesto zielone', 450),
  ('pieczarki', 22),
  ('pieprz', 250),
  ('piers z kurczaka', 110),
  ('poledwica sopocka', 120),
  ('poledwica wolowa', 120),
  ('poledwiczka wieprzowa', 110),
  ('pomidor', 18),
  ('pomidory koktajlowe', 20),
  ('pomidory suszone', 210),
  ('pomidory w puszce', 25),
  ('przyprawa gyros', 250),
  ('przyprawa kebab', 250),
  ('pstrag', 120),
  ('quinoa', 370),
  ('rostbef', 160),
  ('rozmaryn', 130),
  ('rukola', 25),
  ('ryz', 350),
  ('ryz brazowy', 350),
  ('ryz do risotto', 350),
  ('ryz do sushi', 350),
  ('rzodkiewka', 15),
  ('salami', 400),
  ('salata lodowa', 15),
  ('schab', 150),
  ('seler naciowy', 15),
  ('ser cheddar', 400),
  ('ser mozarella', 280),
  ('ser twarog', 130),
  ('ser zolty', 380),
  ('serek alette smietankowy', 250),
  ('smietana', 185),
  ('smietanka 30', 290),
  ('sol', 0),
  ('sos pieczarkowy', 80),
  ('sos sojowy', 60),
  ('sos sweet chilli', 220),
  ('szpinak', 23),
  ('szynka', 110),
  ('szynka wieprzowa', 130),
  ('tortilla', 300),
  ('udka kurczaka', 160),
  ('udziec wolowy', 150),
  ('wieprzowina schab lopatka', 200),
  ('wino biale wytrawne', 80),
  ('wino czerwone wytrawne', 80),
  ('woda', 0),
  ('wolowina', 200),
  ('wolowina ligawa udziec', 150),
  ('wolowina na burgery', 250),
  ('zeberka wieprzowe', 280),
  ('ziele angielskie', 260),
  ('ziemniaki', 77)
) as v(norm, kcal)
where m.nazwa_norm = v.norm and m.kcal_100g is null;

-- 2) Wagi sztuk dla wpisów liczonych w sztukach (potrzebne do przeliczeń).
update skladniki_meta m set waga_sztuki_g = v.waga
from (values
  ('jajko', 55),
  ('tortilla', 60),
  ('bulki do burgerow', 60),
  ('nori', 3),
  ('bulion', 10)
) as v(norm, waga)
where m.nazwa_norm = v.norm and m.waga_sztuki_g is null;

-- 3) Nowe wpisy dla składników bez meta. NOT EXISTS pilnuje duplikatów
--    (także przez aliasy — jeśli ta linia sypnie błędem o typie aliasy,
--    usuń fragment "or v.norm = any(m.aliasy)" i odpal ponownie).
insert into skladniki_meta (nazwa, nazwa_norm, kcal_100g, waga_sztuki_g, jednostka_bazowa)
select v.nazwa, v.norm, v.kcal, v.waga, v.baza
from (values
  ('Amaretto', 'amaretto', 300, null, 'ml'),
  ('Awokado', 'awokado', 160, 140, 'g'),
  ('Bagietka', 'bagietka', 270, 60, 'g'),
  ('Bakłażan', 'baklazan', 25, 300, 'g'),
  ('Banan', 'banan', 90, 120, 'g'),
  ('Batat', 'batat', 90, null, 'g'),
  ('Bazylia suszona', 'bazylia suszona', 250, null, 'g'),
  ('Bekon', 'bekon', 450, null, 'g'),
  ('Biała kiełbasa', 'biala kielbasa', 280, null, 'g'),
  ('Biszkopty podłużne', 'biszkopty podluzne', 390, 5, 'g'),
  ('Boczek wędzony w plastrach', 'boczek wedzony w plastrach', 500, null, 'g'),
  ('Borówki', 'borowki', 55, null, 'g'),
  ('Botwinka z burakami', 'botwinka z burakami', 30, null, 'g'),
  ('Brzoskwinia', 'brzoskwinia', 40, 150, 'g'),
  ('Budyń waniliowy', 'budyn waniliowy', 380, 40, 'g'),
  ('Bulion dashi', 'bulion dashi', 5, null, 'ml'),
  ('Bulion warzywny', 'bulion warzywny', 5, null, 'ml'),
  ('Bulion wołowy', 'bulion wolowy', 5, null, 'ml'),
  ('Bułka', 'bulka', 280, 60, 'g'),
  ('Bułka do hot doga', 'bulka do hot doga', 290, 65, 'g'),
  ('Bułka grahamka', 'bulka grahamka', 260, 60, 'g'),
  ('Bułka panini lub ciabatta', 'bulka panini lub ciabatta', 270, 100, 'g'),
  ('Burak ugotowany', 'burak ugotowany', 45, 100, 'g'),
  ('Cheddar w plastrach', 'cheddar w plastrach', 400, 20, 'g'),
  ('Chili w proszku', 'chili w proszku', 300, null, 'g'),
  ('Chleb pszenny', 'chleb pszenny', 260, 30, 'g'),
  ('Chleb pszenny czerstwy', 'chleb pszenny czerstwy', 260, 30, 'g'),
  ('Chleb żytni', 'chleb zytni', 230, 35, 'g'),
  ('Ciasto francuskie', 'ciasto francuskie', 390, null, 'g'),
  ('Ciecierzyca z puszki', 'ciecierzyca z puszki', 120, null, 'g'),
  ('Cukier puder', 'cukier puder', 400, null, 'g'),
  ('Cukier puder do posypania', 'cukier puder do posypania', 400, null, 'g'),
  ('Cukier trzcinowy', 'cukier trzcinowy', 390, null, 'g'),
  ('Cukier wanilinowy', 'cukier wanilinowy', 400, null, 'g'),
  ('Cukier waniliowy', 'cukier waniliowy', 400, null, 'g'),
  ('Curry w proszku', 'curry w proszku', 320, null, 'g'),
  ('Cynamon', 'cynamon', 250, null, 'g'),
  ('Cynamon mielony', 'cynamon mielony', 250, null, 'g'),
  ('Czekolada deserowa', 'czekolada deserowa', 530, null, 'g'),
  ('Czekolada gorzka', 'czekolada gorzka', 550, null, 'g'),
  ('Czerwona cebula', 'czerwona cebula', 40, null, 'g'),
  ('Czosnek granulowany', 'czosnek granulowany', 330, null, 'g'),
  ('Czosnek świeży', 'czosnek swiezy', 145, 5, 'g'),
  ('Czosnek w proszku', 'czosnek w proszku', 330, null, 'g'),
  ('Daktyle suszone bez pestek', 'daktyle suszone bez pestek', 280, 8, 'g'),
  ('Drożdże', 'drozdze', 100, null, 'g'),
  ('Dymka', 'dymka', 30, 40, 'g'),
  ('Dżem truskawkowy', 'dzem truskawkowy', 240, null, 'g'),
  ('Ekstrakt waniliowy', 'ekstrakt waniliowy', 250, null, 'ml'),
  ('Fasola czerwona z puszki', 'fasola czerwona z puszki', 100, null, 'g'),
  ('Fasolka szparagowa', 'fasolka szparagowa', 30, null, 'g'),
  ('Filet z kurczaka', 'filet z kurczaka', 110, 170, 'g'),
  ('Filet z piersi kurczaka', 'filet z piersi kurczaka', 110, 170, 'g'),
  ('Flaki wołowe', 'flaki wolowe', 90, null, 'g'),
  ('Galaretka truskawkowa w proszku', 'galaretka truskawkowa w proszku', 380, 70, 'g'),
  ('Gnocchi ziemniaczane', 'gnocchi ziemniaczane', 160, null, 'g'),
  ('Gorzka czekolada', 'gorzka czekolada', 550, null, 'g'),
  ('Granola', 'granola', 450, null, 'g'),
  ('Groch łuskany połówki', 'groch luskany polowki', 340, null, 'g'),
  ('Groszek zielony', 'groszek zielony', 80, null, 'g'),
  ('Grzanki', 'grzanki', 400, 5, 'g'),
  ('Herbatniki', 'herbatniki', 450, 8, 'g'),
  ('Hummus', 'hummus', 250, null, 'g'),
  ('Imbir mielony', 'imbir mielony', 335, null, 'g'),
  ('Jabłka', 'jablka', 50, 180, 'g'),
  ('Jajka', 'jajka', 143, 55, 'g'),
  ('Jajko (do posmarowania)', 'jajko do posmarowania', 143, 55, 'g'),
  ('Jajko (do wersji madame)', 'jajko do wersji madame', 143, 55, 'g'),
  ('Jajko ugotowane na twardo', 'jajko ugotowane na twardo', 143, 55, 'g'),
  ('Jarmuż', 'jarmuz', 50, null, 'g'),
  ('Jogurt grecki', 'jogurt grecki', 100, null, 'g'),
  ('Kajmak (masa krówkowa)', 'kajmak masa krowkowa', 320, null, 'g'),
  ('Kakao', 'kakao', 380, null, 'g'),
  ('Kasza kuskus', 'kasza kuskus', 350, null, 'g'),
  ('Kasza manna', 'kasza manna', 350, null, 'g'),
  ('Kawa espresso', 'kawa espresso', 2, null, 'ml'),
  ('Kefir', 'kefir', 50, null, 'g'),
  ('Kiełbasa wiejska', 'kielbasa wiejska', 320, null, 'g'),
  ('Kiwi', 'kiwi', 60, 75, 'g'),
  ('Kmin rzymski mielony', 'kmin rzymski mielony', 375, null, 'g'),
  ('Kolendra', 'kolendra', 25, null, 'g'),
  ('Kolendra świeża', 'kolendra swieza', 25, null, 'g'),
  ('Koperek', 'koperek', 40, null, 'g'),
  ('Krakersy', 'krakersy', 450, 5, 'g'),
  ('Krem balsamiczny', 'krem balsamiczny', 150, null, 'g'),
  ('Krewetki', 'krewetki', 85, null, 'g'),
  ('Kukurydza do prażenia', 'kukurydza do prazenia', 370, null, 'g'),
  ('Kukurydza konserwowa', 'kukurydza konserwowa', 90, null, 'g'),
  ('Kukurydza z puszki', 'kukurydza z puszki', 90, null, 'g'),
  ('Kumin mielony', 'kumin mielony', 375, null, 'g'),
  ('Laska wanilii', 'laska wanilii', 300, 5, 'g'),
  ('Likier pomarańczowy (cointreau lub grand marnier)', 'likier pomaranczowy cointreau lub grand marnier', 320, null, 'ml'),
  ('Limonka', 'limonka', 30, 70, 'g'),
  ('Liście sałaty', 'liscie salaty', 15, 10, 'g'),
  ('Listki mięty', 'listki miety', 45, 1, 'g'),
  ('Łosoś wędzony', 'losos wedzony', 180, null, 'g'),
  ('Mak', 'mak', 520, null, 'g'),
  ('Mąka pszenna', 'maka pszenna', 360, null, 'g'),
  ('Makaron nitki', 'makaron nitki', 360, null, 'g'),
  ('Makaron ryżowy', 'makaron ryzowy', 360, null, 'g'),
  ('Makrela wędzona', 'makrela wedzona', 220, null, 'g'),
  ('Maliny', 'maliny', 35, null, 'g'),
  ('Mascarpone', 'mascarpone', 430, null, 'g'),
  ('Masło do smażenia', 'maslo do smazenia', 735, null, 'g'),
  ('Masło orzechowe', 'maslo orzechowe', 600, null, 'g'),
  ('Masło roztopione', 'maslo roztopione', 735, null, 'g'),
  ('Mielona wołowina', 'mielona wolowina', 220, null, 'g'),
  ('Mięso mielone wołowe', 'mieso mielone wolowe', 220, null, 'g'),
  ('Mięso mielone wołowo-wieprzowe', 'mieso mielone wolowo wieprzowe', 250, null, 'g'),
  ('Mięso z kurczaka (udka)', 'mieso z kurczaka udka', 160, null, 'g'),
  ('Mieszanka sałat', 'mieszanka salat', 15, null, 'g'),
  ('Mięta', 'mieta', 45, 1, 'g'),
  ('Mięta lub koperek', 'mieta lub koperek', 45, null, 'g'),
  ('Migdały', 'migdaly', 580, null, 'g'),
  ('Mini bułki do burgerów', 'mini bulki do burgerow', 290, 30, 'g'),
  ('Mini bułki do hot dogów', 'mini bulki do hot dogow', 290, 30, 'g'),
  ('Mini mozzarella (ciliegine)', 'mini mozzarella ciliegine', 250, 8, 'g'),
  ('Mini parówki', 'mini parowki', 260, 20, 'g'),
  ('Mleko kokosowe', 'mleko kokosowe', 180, null, 'ml'),
  ('Mleko skondensowane słodzone', 'mleko skondensowane slodzone', 320, null, 'g'),
  ('Mleko w proszku', 'mleko w proszku', 500, null, 'g'),
  ('Mozzarella', 'mozzarella', 280, null, 'g'),
  ('Mozzarella tarta', 'mozzarella tarta', 280, null, 'g'),
  ('Mrożone maliny', 'mrozone maliny', 35, null, 'g'),
  ('Mrożone truskawki', 'mrozone truskawki', 33, null, 'g'),
  ('Nachosy kukurydziane', 'nachosy kukurydziane', 500, null, 'g'),
  ('Nasiona chia', 'nasiona chia', 490, null, 'g'),
  ('Ocet balsamiczny', 'ocet balsamiczny', 90, null, 'ml'),
  ('Ocet winny', 'ocet winny', 20, null, 'ml'),
  ('Ocet winny czerwony', 'ocet winny czerwony', 20, null, 'ml'),
  ('Ogórek konserwowy', 'ogorek konserwowy', 12, 60, 'g'),
  ('Ogórek świeży', 'ogorek swiezy', 15, null, 'g'),
  ('Ogórek zielony', 'ogorek zielony', 15, null, 'g'),
  ('Ogórki kiszone', 'ogorki kiszone', 12, 80, 'g'),
  ('Olej do smażenia', 'olej do smazenia', 884, null, 'ml'),
  ('Olej roślinny', 'olej roslinny', 884, null, 'ml'),
  ('Olej rzepakowy', 'olej rzepakowy', 884, null, 'ml'),
  ('Olej sezamowy', 'olej sezamowy', 884, null, 'ml'),
  ('Oliwa z oliwek', 'oliwa z oliwek', 884, null, 'ml'),
  ('Oliwa z oliwek extra virgin', 'oliwa z oliwek extra virgin', 884, null, 'ml'),
  ('Oregano suszone', 'oregano suszone', 270, null, 'g'),
  ('Orzechy nerkowca', 'orzechy nerkowca', 550, null, 'g'),
  ('Orzechy włoskie', 'orzechy wloskie', 650, null, 'g'),
  ('Orzeszki ziemne niesolone', 'orzeszki ziemne niesolone', 570, null, 'g'),
  ('Owoce sezonowe', 'owoce sezonowe', 45, null, 'g'),
  ('Owoce sezonowe (truskawki, maliny)', 'owoce sezonowe truskawki maliny', 45, null, 'g'),
  ('Papier ryżowy', 'papier ryzowy', 340, 10, 'g'),
  ('Papryczka chili', 'papryczka chili', 40, 15, 'g'),
  ('Papryczka jalapeño', 'papryczka jalapeno', 30, 15, 'g'),
  ('Papryka ostra mielona', 'papryka ostra mielona', 290, null, 'g'),
  ('Papryka ostra w proszku', 'papryka ostra w proszku', 290, null, 'g'),
  ('Papryka słodka mielona', 'papryka slodka mielona', 290, null, 'g'),
  ('Papryka słodka w proszku', 'papryka slodka w proszku', 290, null, 'g'),
  ('Parmezan tarty', 'parmezan tarty', 400, null, 'g'),
  ('Parówki', 'parowki', 260, 50, 'g'),
  ('Parówki cielęce', 'parowki cielece', 230, 50, 'g'),
  ('Passata pomidorowa', 'passata pomidorowa', 30, null, 'ml'),
  ('Pasta miso', 'pasta miso', 200, null, 'g'),
  ('Pesto bazyliowe', 'pesto bazyliowe', 450, null, 'g'),
  ('Pieczywo', 'pieczywo', 250, 30, 'g'),
  ('Pieczywo do podania', 'pieczywo do podania', 250, 30, 'g'),
  ('Pieczywo pełnoziarniste', 'pieczywo pelnoziarniste', 230, 35, 'g'),
  ('Pieczywo tostowe', 'pieczywo tostowe', 270, 25, 'g'),
  ('Pieprz czarny', 'pieprz czarny', 250, null, 'g'),
  ('Pieprz czarny mielony', 'pieprz czarny mielony', 250, null, 'g'),
  ('Pieprz ziarnisty', 'pieprz ziarnisty', 250, null, 'g'),
  ('Pietruszka korzeń', 'pietruszka korzen', 40, null, 'g'),
  ('Płatki chili', 'platki chili', 300, null, 'g'),
  ('Płatki kukurydziane', 'platki kukurydziane', 380, null, 'g'),
  ('Płatki owsiane', 'platki owsiane', 370, null, 'g'),
  ('Pomarańcza', 'pomarancza', 45, 200, 'g'),
  ('Pomidorki koktajlowe', 'pomidorki koktajlowe', 20, 15, 'g'),
  ('Pomidory', 'pomidory', 18, 120, 'g'),
  ('Pomidory dojrzałe', 'pomidory dojrzale', 18, 120, 'g'),
  ('Pomidory krojone z puszki', 'pomidory krojone z puszki', 25, null, 'g'),
  ('Pomidory z puszki', 'pomidory z puszki', 25, null, 'g'),
  ('Por', 'por', 60, 150, 'g'),
  ('Proszek do pieczenia', 'proszek do pieczenia', 100, null, 'g'),
  ('Przyprawa do mięsa mielonego', 'przyprawa do miesa mielonego', 250, null, 'g'),
  ('Przyprawa do tacos', 'przyprawa do tacos', 250, null, 'g'),
  ('Rodzynki', 'rodzynki', 300, null, 'g'),
  ('Rozmaryn świeży', 'rozmaryn swiezy', 130, 3, 'g'),
  ('Ryż basmati', 'ryz basmati', 350, null, 'g'),
  ('Ryż jaśminowy', 'ryz jasminowy', 350, null, 'g'),
  ('Ryż krótkoziarnisty', 'ryz krotkoziarnisty', 350, null, 'g'),
  ('Sałata', 'salata', 15, 10, 'g'),
  ('Sałata rzymska', 'salata rzymska', 15, 300, 'g'),
  ('Seler', 'seler', 25, null, 'g'),
  ('Ser camembert', 'ser camembert', 300, 120, 'g'),
  ('Ser cheddar tarty', 'ser cheddar tarty', 400, null, 'g'),
  ('Ser cheddar w plastrach', 'ser cheddar w plastrach', 400, 20, 'g'),
  ('Ser feta', 'ser feta', 260, null, 'g'),
  ('Ser feta lub queso fresco', 'ser feta lub queso fresco', 260, null, 'g'),
  ('Ser gouda', 'ser gouda', 360, null, 'g'),
  ('Ser gruyère', 'ser gruyere', 410, null, 'g'),
  ('Ser halloumi', 'ser halloumi', 320, null, 'g'),
  ('Ser kozi', 'ser kozi', 360, null, 'g'),
  ('Ser mascarpone', 'ser mascarpone', 430, null, 'g'),
  ('Ser mozzarella', 'ser mozzarella', 280, null, 'g'),
  ('Ser mozzarella tarty', 'ser mozzarella tarty', 280, null, 'g'),
  ('Ser pleśniowy gorgonzola', 'ser plesniowy gorgonzola', 350, null, 'g'),
  ('Ser twarogowy na sernik', 'ser twarogowy na sernik', 160, null, 'g'),
  ('Ser żółty (gouda)', 'ser zolty gouda', 380, null, 'g'),
  ('Ser żółty (np. gouda)', 'ser zolty np gouda', 380, null, 'g'),
  ('Ser żółty starty', 'ser zolty starty', 380, null, 'g'),
  ('Ser żółty tarty', 'ser zolty tarty', 380, null, 'g'),
  ('Serek kremowy', 'serek kremowy', 250, null, 'g'),
  ('Serek mascarpone', 'serek mascarpone', 430, null, 'g'),
  ('Serek śmietankowy', 'serek smietankowy', 250, null, 'g'),
  ('Serek topiony', 'serek topiony', 300, null, 'g'),
  ('Serek waniliowy', 'serek waniliowy', 130, null, 'g'),
  ('Sezam', 'sezam', 570, null, 'g'),
  ('Siemię lniane', 'siemie lniane', 500, null, 'g'),
  ('Skrobia kukurydziana', 'skrobia kukurydziana', 350, null, 'g'),
  ('Skrobia ziemniaczana', 'skrobia ziemniaczana', 340, null, 'g'),
  ('Skrzydełka z kurczaka', 'skrzydelka z kurczaka', 190, null, 'g'),
  ('Śmietana 18%', 'smietana 18', 185, null, 'ml'),
  ('Śmietana 30%', 'smietana 30', 290, null, 'ml'),
  ('Śmietana kremówka 30%', 'smietana kremowka 30', 290, null, 'ml'),
  ('Sok malinowy', 'sok malinowy', 50, null, 'ml'),
  ('Sok z cytryny', 'sok z cytryny', 25, null, 'ml'),
  ('Sok z limonki', 'sok z limonki', 25, null, 'ml'),
  ('Sól i pieprz', 'sol i pieprz', 100, null, 'g'),
  ('Sól morska', 'sol morska', 0, null, 'g'),
  ('Sos BBQ', 'sos bbq', 150, null, 'g'),
  ('Sos burgerowy', 'sos burgerowy', 350, null, 'g'),
  ('Sos cezar', 'sos cezar', 450, null, 'g'),
  ('Sos czosnkowy', 'sos czosnkowy', 350, null, 'g'),
  ('Sos pomidorowy', 'sos pomidorowy', 60, null, 'g'),
  ('Świeża bazylia', 'swieza bazylia', 25, 2, 'g'),
  ('Świeża mięta', 'swieza mieta', 45, null, 'g'),
  ('Świeża natka pietruszki', 'swieza natka pietruszki', 40, null, 'g'),
  ('Świeżo mielony pieprz', 'swiezo mielony pieprz', 250, null, 'g'),
  ('Świeży koperek', 'swiezy koperek', 40, null, 'g'),
  ('Syrop klonowy', 'syrop klonowy', 260, null, 'ml'),
  ('Szczypiorek', 'szczypiorek', 30, null, 'g'),
  ('Szczypta soli', 'szczypta soli', 0, null, 'g'),
  ('Szynka dojrzewająca', 'szynka dojrzewajaca', 250, 15, 'g'),
  ('Szynka parmeńska', 'szynka parmenska', 250, 15, 'g'),
  ('Szynka w kostce', 'szynka w kostce', 110, null, 'g'),
  ('Szynka w plastrach', 'szynka w plastrach', 110, 15, 'g'),
  ('Tofu naturalne', 'tofu naturalne', 120, null, 'g'),
  ('Tortilla pszenna', 'tortilla pszenna', 300, 60, 'g'),
  ('Tortille pszenne', 'tortille pszenne', 300, 60, 'g'),
  ('Tortille pszenne małe', 'tortille pszenne male', 300, 30, 'g'),
  ('Truskawki', 'truskawki', 33, null, 'g'),
  ('Tuńczyk w sosie własnym', 'tunczyk w sosie wlasnym', 110, null, 'g'),
  ('Twaróg', 'twarog', 130, null, 'g'),
  ('Twaróg półtłusty', 'twarog poltlusty', 130, null, 'g'),
  ('Twaróg sernikowy', 'twarog sernikowy', 160, null, 'g'),
  ('Twarożek', 'twarozek', 130, null, 'g'),
  ('Tymianek', 'tymianek', 280, null, 'g'),
  ('Winogrona', 'winogrona', 70, null, 'g'),
  ('Wiórki kokosowe', 'wiorki kokosowe', 660, null, 'g'),
  ('Wiórki kokosowe do obtoczenia', 'wiorki kokosowe do obtoczenia', 660, null, 'g'),
  ('Włoszczyzna', 'wloszczyzna', 40, null, 'g'),
  ('Włoszczyzna (marchew, pietruszka, seler, por)', 'wloszczyzna marchew pietruszka seler por', 40, null, 'g'),
  ('Woda gazowana', 'woda gazowana', 0, null, 'ml'),
  ('Wodorosty wakame', 'wodorosty wakame', 45, null, 'g'),
  ('Wołowina gulaszowa', 'wolowina gulaszowa', 160, null, 'g'),
  ('Wykałaczki', 'wykalaczki', 0, 0, 'g'),
  ('Ząbek czosnku', 'zabek czosnku', 145, 5, 'g'),
  ('Zakwas na żur', 'zakwas na zur', 30, null, 'ml'),
  ('Żeberka wędzone', 'zeberka wedzone', 300, null, 'g'),
  ('Żelatyna', 'zelatyna', 340, null, 'g'),
  ('Ziarna kukurydzy do popcornu', 'ziarna kukurydzy do popcornu', 370, null, 'g'),
  ('Ziemniak', 'ziemniak', 77, 150, 'g'),
  ('Zioła prowansalskie', 'ziola prowansalskie', 260, null, 'g'),
  ('Żółtka', 'zoltka', 320, 18, 'g'),
  ('Żółtko jajka', 'zoltko jajka', 320, 18, 'g'),
  ('Żurawina (konfitura)', 'zurawina konfitura', 250, null, 'g')
) as v(nazwa, norm, kcal, waga, baza)
where not exists (
  select 1 from skladniki_meta m
  where m.nazwa_norm = v.norm or v.norm = any(m.aliasy)
);

-- 4) Kontrola: składniki z przepisów nadal bez kcal (powinno być ~0).
select count(*) as skladniki_bez_kcal from (
  select distinct "Składnik" from dania where "Składnik" is not null and "Składnik" <> ''
) s
left join skladniki_meta m on m.nazwa_norm = trim(regexp_replace(lower(translate(s."Składnik",
  'ąćęłńóśźżĄĆĘŁŃÓŚŹŻ', 'acelnoszzACELNOSZZ')), '[^a-z0-9]+', ' ', 'g'))
where m.kcal_100g is null;
