-- ════════════════════════════════════════════════════════════
-- Kuchnia (kraj pochodzenia) i poziom trudności dla wszystkich dań
-- Uruchom w Supabase: SQL Editor → New query → wklej → Run
--
-- Wymaga wcześniejszej `migracja_kuchnia_poziom.sql` (kolumny `kuchnia`
-- i `poziom` w tabeli `dania`).
--
-- Dlaczego plik, a nie skrypt: tryb `kuchnie` pyta o to Claude'a przez API
-- i kosztuje — przy pierwszym podejściu wyczerpał kredyty na 16 z 30 paczek.
-- Przypisania poniżej powstały bez API, więc odpalenie tego pliku nic nie
-- kosztuje.
--
-- Wartości pochodzą z zamkniętych list w skrypty/wspolne.js:
--   kuchnia — KUCHNIE (20 pozycji)
--   poziom  — POZIOMY: latwe | srednie | trudne
-- Etykiety do wyświetlenia (flagi, kolory) siedzą w src/etykiety.js.
--
-- BEZPIECZNIK: `coalesce` sprawia, że wypełniamy TYLKO puste kolumny.
-- 37 dań kuchni chińskiej dostało te pola już przy generowaniu i ten plik
-- ich nie tknie. Z tego samego powodu można go odpalać wielokrotnie —
-- za drugim razem nie zrobi nic.
--
-- `btrim` po stronie bazy, bo co najmniej jedno danie ma spację na końcu
-- nazwy („Jajka z papryką "), a nazwy poniżej są przycięte.
--
-- `dania` to wiersz na SKŁADNIK, więc jedno danie to kilkanaście wierszy —
-- update trafia we wszystkie naraz i tak ma być (dokładnie tak działają tam
-- `rodzaj`, `czas_minuty` i `kcal`).
-- ════════════════════════════════════════════════════════════

with przypisania(danie, kuchnia, poziom) as (
  values
    ('Affogato al caffè', 'wloska', 'latwe'),
    ('Amaretti', 'wloska', 'srednie'),
    ('Arancini z ryżu', 'wloska', 'trudne'),
    ('Babka piaskowa', 'polska', 'srednie'),
    ('Bajgle z serkiem i ogórkiem', 'miedzynarodowa', 'latwe'),
    ('Bakłażan duszony w gochujangu', 'koreanska', 'srednie'),
    ('Bakłażan w panko', 'japonska', 'srednie'),
    ('Bakłażan w sosie yuxiang', 'chinska', 'srednie'),
    ('Banany smażone z miodem i cynamonem', 'miedzynarodowa', 'latwe'),
    ('Banany w cieście naleśnikowym', 'miedzynarodowa', 'latwe'),
    ('Barszcz biały z białą kiełbasą', 'polska', 'srednie'),
    ('Barszcz czerwony', 'polska', 'srednie'),
    ('Barszcz ukraiński', 'ukrainska', 'srednie'),
    ('Beza Pavlova z owocami', 'miedzynarodowa', 'trudne'),
    ('Bibimbap z tofu', 'koreanska', 'srednie'),
    ('Bibimbap z wołowiną', 'koreanska', 'srednie'),
    ('Bigos', 'polska', 'srednie'),
    ('Bitki wołowe w sosie własnym', 'polska', 'srednie'),
    ('Bocconcini w oliwie z ziołami', 'wloska', 'latwe'),
    ('Boeuf Strogonow', 'miedzynarodowa', 'srednie'),
    ('Bomboloni', 'wloska', 'trudne'),
    ('Botwinka z jajkiem', 'polska', 'latwe'),
    ('Breakfast Burrito', 'amerykanska', 'latwe'),
    ('Brownie czekoladowe', 'amerykanska', 'latwe'),
    ('Brownie z patelni', 'amerykanska', 'latwe'),
    ('Bruschetta z mozzarellą i rukolą', 'wloska', 'latwe'),
    ('Bruschetta z pieczarkami', 'wloska', 'latwe'),
    ('Bruschetta z pomidorami i bazylią', 'wloska', 'latwe'),
    ('Budae jjigae z parówkami i tofu', 'koreanska', 'latwe'),
    ('Budyń czekoladowy', 'polska', 'latwe'),
    ('Budyń mango z tapioką', 'chinska', 'latwe'),
    ('Budyń waniliowy z owocami', 'polska', 'latwe'),
    ('Bulgogi wieprzowe w gochujangu', 'koreanska', 'srednie'),
    ('Bulgogi wołowe', 'koreanska', 'srednie'),
    ('Bułeczki bao z nadzieniem wieprzowym', 'chinska', 'trudne'),
    ('Bułeczki jak z Maka', 'amerykanska', 'trudne'),
    ('Bungeoppang z pastą z czerwonej fasoli', 'koreanska', 'trudne'),
    ('Buraczki', 'polska', 'latwe'),
    ('Burger wołowy', 'amerykanska', 'srednie'),
    ('Burgery z soczewicy', 'miedzynarodowa', 'srednie'),
    ('Burrito z mieloną wołowiną', 'meksykanska', 'srednie'),
    ('Butter Chicken', 'indyjska', 'srednie'),
    ('Calzone z szynką i ricottą', 'wloska', 'trudne'),
    ('Camembert pieczony z żurawiną', 'francuska', 'latwe'),
    ('Cannelloni ze szpinakiem i ricottą', 'wloska', 'srednie'),
    ('Cannoli siciliane', 'wloska', 'trudne'),
    ('Cantuccini z migdałami', 'wloska', 'srednie'),
    ('Caponata z bakłażana', 'wloska', 'srednie'),
    ('Carpaccio wołowe z rukolą', 'wloska', 'latwe'),
    ('Carpaccio z buraka na grzankach', 'wloska', 'latwe'),
    ('Cebulowa (po francusku)', 'francuska', 'srednie'),
    ('Chałka z masłem i miodem', 'polska', 'latwe'),
    ('Chia pudding z mango', 'miedzynarodowa', 'latwe'),
    ('Chilli con carne', 'meksykanska', 'srednie'),
    ('Chińska zupa pikantno kwaśna', 'chinska', 'srednie'),
    ('Chipsy z buraka', 'miedzynarodowa', 'latwe'),
    ('Chipsy z jarmużu', 'miedzynarodowa', 'latwe'),
    ('Chipsy z tortilli z dipem jogurtowym', 'meksykanska', 'latwe'),
    ('Chleb w jajku', 'polska', 'latwe'),
    ('Chłodnik litewski', 'polska', 'latwe'),
    ('Chłodnik ogórkowy z koperkiem', 'polska', 'latwe'),
    ('Chow fun z wołowiną', 'chinska', 'srednie'),
    ('Chow mein z kurczakiem', 'chinska', 'srednie'),
    ('Chrupiąca ciecierzyca z piekarnika', 'miedzynarodowa', 'latwe'),
    ('Chrupiące chili w oleju', 'chinska', 'srednie'),
    ('Chrupiące kąski z kurczaka', 'miedzynarodowa', 'srednie'),
    ('Chrupiące wontony smażone', 'chinska', 'trudne'),
    ('Ciambellone', 'wloska', 'srednie'),
    ('Ciasteczka z wróżbą', 'chinska', 'srednie'),
    ('Ciasto czekoladowe z wiśniami', 'polska', 'srednie'),
    ('Ciasto drożdżowe z kruszonką', 'polska', 'trudne'),
    ('Ciasto francuskie z jabłkiem i cynamonem', 'miedzynarodowa', 'latwe'),
    ('Ciasto marchewkowe', 'amerykanska', 'srednie'),
    ('Ciasto ucierane z owocami', 'polska', 'latwe'),
    ('Colesław', 'amerykanska', 'latwe'),
    ('Cornetto z kremem', 'wloska', 'trudne'),
    ('Cotoletta alla milanese', 'wloska', 'srednie'),
    ('Crème brûlée', 'francuska', 'trudne'),
    ('Crespelle zapiekane z szynką i beszamelem', 'wloska', 'srednie'),
    ('Croque Monsieur/Madame', 'francuska', 'latwe'),
    ('Crostata z dżemem morelowym', 'wloska', 'srednie'),
    ('Crostini z wątróbką drobiową', 'wloska', 'srednie'),
    ('Cukinia w panierce', 'polska', 'srednie'),
    ('Curry z ciecierzycy i szpinaku', 'indyjska', 'srednie'),
    ('Daktyle z masłem orzechowym', 'miedzynarodowa', 'latwe'),
    ('Deser lodowy z gorącymi malinami', 'miedzynarodowa', 'latwe'),
    ('Deser z mascarpone, herbatnikami i owocami', 'wloska', 'latwe'),
    ('Deska serów i wędlin', 'miedzynarodowa', 'latwe'),
    ('Domowe hot dogi z prażoną cebulką', 'amerykanska', 'latwe'),
    ('Dorsz panierowany', 'polska', 'srednie'),
    ('Dorsz w sosie cytrynowym', 'miedzynarodowa', 'srednie'),
    ('Dorsz z piekarnika', 'polska', 'latwe'),
    ('Duszona wołowina z warzywami korzeniowymi', 'polska', 'srednie'),
    ('Duszone żeberka wołowe po koreańsku', 'koreanska', 'trudne'),
    ('Falafel z sosem tahini', 'bliskowschodnia', 'trudne'),
    ('Farfalle z łososiem i groszkiem', 'wloska', 'latwe'),
    ('Farinata z ciecierzycy', 'wloska', 'srednie'),
    ('Fasolka po bretońsku', 'polska', 'srednie'),
    ('Faszerowana pierś kurczaka', 'miedzynarodowa', 'srednie'),
    ('Faszerowane papryczki serkiem', 'miedzynarodowa', 'latwe'),
    ('Faworki', 'polska', 'trudne'),
    ('Fette biscottate z dżemem i masłem', 'wloska', 'latwe'),
    ('Fettuccine Alfredo', 'wloska', 'latwe'),
    ('Filet z indyka w sosie grzybowym', 'polska', 'srednie'),
    ('Flaki', 'polska', 'trudne'),
    ('Focaccia z pomidorkami i oliwkami', 'wloska', 'trudne'),
    ('Focaccia z rozmarynem i solą morską', 'wloska', 'trudne'),
    ('Frittata z cukinią i parmezanem', 'wloska', 'latwe'),
    ('Frittata z ziemniakami i cebulą', 'wloska', 'latwe'),
    ('Fritto misto z owoców morza', 'wloska', 'trudne'),
    ('Frytki z batatów', 'amerykanska', 'latwe'),
    ('Frytki z majonezem gochujang', 'koreanska', 'latwe'),
    ('Galaretka z owocami', 'polska', 'latwe'),
    ('Gazpacho', 'hiszpanska', 'latwe'),
    ('Gelato pistacjowe', 'wloska', 'trudne'),
    ('Gnocchi alla sorrentina', 'wloska', 'srednie'),
    ('Gnocchi z masłem, czosnkiem i parmezanem', 'wloska', 'latwe'),
    ('Gnocchi z sosem pomidorowym i mozzarellą', 'wloska', 'latwe'),
    ('Gochujang jjigae z cukinią', 'koreanska', 'srednie'),
    ('Gofrowe kąski', 'miedzynarodowa', 'latwe'),
    ('Gofry na słono z serem i szynką', 'miedzynarodowa', 'latwe'),
    ('Gofry z owocami i bitą śmietaną', 'miedzynarodowa', 'latwe'),
    ('Golonka pieczona w piwie', 'polska', 'trudne'),
    ('Gołąbki w sosie pomidorowym', 'polska', 'trudne'),
    ('Granita cytrynowa', 'wloska', 'latwe'),
    ('Grissini z szynką parmeńską', 'wloska', 'latwe'),
    ('Grochówka', 'polska', 'srednie'),
    ('Grzanki czosnkowe z serem', 'polska', 'latwe'),
    ('Grzanki z awokado, jajkiem i pomidorem', 'miedzynarodowa', 'latwe'),
    ('Grzanki z serem żółtym i pomidorem', 'polska', 'latwe'),
    ('Guacamole', 'meksykanska', 'latwe'),
    ('Gulasz domowy (sos mięsny)', 'polska', 'srednie'),
    ('Gulasz wieprzowy z kluskami', 'polska', 'srednie'),
    ('Gulasz z indyka z papryką', 'wegierska', 'srednie'),
    ('Gulaszowa', 'wegierska', 'srednie'),
    ('Gyros domowy z sosem czosnkowym', 'grecka', 'srednie'),
    ('Hotteok z cynamonem', 'koreanska', 'trudne'),
    ('Huevos Rancheros', 'meksykanska', 'srednie'),
    ('Hummus z pieczonym burakiem', 'bliskowschodnia', 'latwe'),
    ('Indyk pieczony z warzywami', 'polska', 'srednie'),
    ('Insalata tricolore', 'wloska', 'latwe'),
    ('Involtini cielęce w sosie pomidorowym', 'wloska', 'srednie'),
    ('Jabłecznik z kruszonką', 'polska', 'srednie'),
    ('Jabłka pieczone z cynamonem', 'polska', 'latwe'),
    ('Jabłka w cieście', 'polska', 'srednie'),
    ('Jaglanka z jabłkiem i cynamonem', 'polska', 'latwe'),
    ('Jajecznica', 'polska', 'latwe'),
    ('Jajecznica z boczkiem i szczypiorkiem', 'polska', 'latwe'),
    ('Jajka faszerowane', 'polska', 'srednie'),
    ('Jajka na miękko', 'miedzynarodowa', 'latwe'),
    ('Jajka na twardo z majonezem', 'polska', 'latwe'),
    ('Jajka po benedyktyńsku', 'amerykanska', 'trudne'),
    ('Jajka po turecku*', 'turecka', 'srednie'),
    ('Jajka przepiórcze w panierce', 'miedzynarodowa', 'srednie'),
    ('Jajka sadzone z boczkiem', 'polska', 'latwe'),
    ('Jajka sadzone z ziemniakami z patelni i mizerią', 'polska', 'latwe'),
    ('Jajka smażone z pomidorami po chińsku', 'chinska', 'latwe'),
    ('Jajka w koszulce na grzance', 'miedzynarodowa', 'srednie'),
    ('Jajka w majonezie ze szczypiorkiem', 'polska', 'latwe'),
    ('Jajka z papryką', 'polska', 'latwe'),
    ('Jajka zapiekane w awokado', 'miedzynarodowa', 'latwe'),
    ('Japchae z wołowiną', 'koreanska', 'srednie'),
    ('Jarzynowa', 'polska', 'latwe'),
    ('Jogurt grecki z miodem i orzechami', 'grecka', 'latwe'),
    ('Kaczka pieczona z jabłkami', 'polska', 'trudne'),
    ('Kaczka po pekińsku', 'chinska', 'trudne'),
    ('Kalafior marynowany z oliwkami', 'wloska', 'latwe'),
    ('Kalafiorowa', 'polska', 'latwe'),
    ('Kalmary w sosie gochujang', 'koreanska', 'srednie'),
    ('Kanapki na ciepło z mozzarellą, pomidorem i szynką', 'wloska', 'latwe'),
    ('Kanapki z jajkiem', 'polska', 'latwe'),
    ('Kanapki z łososiem i twarożkiem', 'miedzynarodowa', 'latwe'),
    ('Kanapki z pastą z ciecierzycy', 'bliskowschodnia', 'latwe'),
    ('Kanapki z pastą z pieczonej papryki', 'miedzynarodowa', 'latwe'),
    ('Kanapki z pastą z tuńczyka', 'miedzynarodowa', 'latwe'),
    ('Kanapki z pasztetem i ogórkiem kiszonym', 'polska', 'latwe'),
    ('Kanapki z serem i wędliną', 'polska', 'latwe'),
    ('Kanapki z twarogiem i miodem', 'polska', 'latwe'),
    ('Kanapki zapiekane z pieczarkami', 'polska', 'latwe'),
    ('Kapsalon', 'miedzynarodowa', 'srednie'),
    ('Kapuśniak', 'polska', 'srednie'),
    ('Karczochy smażone', 'wloska', 'srednie'),
    ('Karkówka pieczona w piekarniku', 'polska', 'srednie'),
    ('Karpatka', 'polska', 'trudne'),
    ('Kasza bulgur z kurczakiem, papryką i sosem jogurtowym', 'bliskowschodnia', 'srednie'),
    ('Kasza manna na mleku', 'polska', 'latwe'),
    ('Kasza manna z sokiem malinowym', 'polska', 'latwe'),
    ('Kaszka kukurydziana z owocami', 'polska', 'latwe'),
    ('Kiełki sojowe z sezamem', 'koreanska', 'latwe'),
    ('Kimbap warzywny', 'koreanska', 'srednie'),
    ('Kimbap z tuńczykiem', 'koreanska', 'srednie'),
    ('Kimchi jjigae z wieprzowiną', 'koreanska', 'srednie'),
    ('Kisiel owocowy', 'polska', 'latwe'),
    ('Klopsiki szwedzkie w sosie śmietanowym', 'miedzynarodowa', 'srednie'),
    ('Klopsiki w sosie pomidorowym', 'polska', 'srednie'),
    ('Kluski lane na mleku', 'polska', 'latwe'),
    ('Kluski z serem i skwarkami', 'polska', 'srednie'),
    ('Koktajl bananowo-truskawkowy', 'miedzynarodowa', 'latwe'),
    ('Koktajl owocowy z jogurtem', 'miedzynarodowa', 'latwe'),
    ('Kopytka z cebulką', 'polska', 'srednie'),
    ('Koreańska owsianka ryżowa z kurczakiem', 'koreanska', 'srednie'),
    ('Koreańska zupa z wodorostów', 'koreanska', 'latwe'),
    ('Koreański gulasz z kurczaka i ziemniaków', 'koreanska', 'srednie'),
    ('Koreański omlet parowany', 'koreanska', 'latwe'),
    ('Koreańskie kluski sujebi w bulionie', 'koreanska', 'srednie'),
    ('Koreczki', 'polska', 'latwe'),
    ('Kotlet de volaille', 'polska', 'trudne'),
    ('Kotlet schabowy', 'polska', 'srednie'),
    ('Kotlety mielone', 'polska', 'srednie'),
    ('Kotlety z ciecierzycy', 'miedzynarodowa', 'srednie'),
    ('Kotlety z kaszy gryczanej', 'polska', 'srednie'),
    ('Krakersy z serkiem i ogórkiem', 'miedzynarodowa', 'latwe'),
    ('Krążki cebulowe', 'amerykanska', 'trudne'),
    ('Krążki kalmarów smażone', 'wloska', 'trudne'),
    ('Krem budyniowy z bananami', 'polska', 'latwe'),
    ('Krem z cukinii z miętą', 'miedzynarodowa', 'latwe'),
    ('Krem z kalafiora z migdałami', 'miedzynarodowa', 'latwe'),
    ('Krem z karczochów', 'wloska', 'srednie'),
    ('Krem z mascarpone i kajmaku', 'wloska', 'latwe'),
    ('Krem z zielonego groszku z miętą', 'miedzynarodowa', 'latwe'),
    ('Krem ze szparagów', 'francuska', 'srednie'),
    ('Kremówka', 'polska', 'trudne'),
    ('Krewetki smażone z czosnkiem', 'hiszpanska', 'latwe'),
    ('Krewetki w sosie chili po chińsku', 'chinska', 'srednie'),
    ('Krewetki w sosie czosnkowym z makaronem', 'wloska', 'latwe'),
    ('Krokiety z kapustą kiszoną i grzybami', 'polska', 'trudne'),
    ('Krokiety z mięsem', 'polska', 'trudne'),
    ('Krokiety z pieczarkami', 'polska', 'trudne'),
    ('Krupnik', 'polska', 'srednie'),
    ('Kulki kokosowe', 'miedzynarodowa', 'latwe'),
    ('Kulki mocy z płatków owsianych', 'miedzynarodowa', 'latwe'),
    ('Kulki mozzarelli w szynce parmeńskiej', 'wloska', 'latwe'),
    ('Kulki owsiane z masłem orzechowym i miodem', 'miedzynarodowa', 'latwe'),
    ('Kulki serowe w panierce', 'miedzynarodowa', 'srednie'),
    ('Kurczak curry z ryżem', 'indyjska', 'srednie'),
    ('Kurczak dakgalbi z warzywami', 'koreanska', 'srednie'),
    ('Kurczak generała Tso', 'chinska', 'trudne'),
    ('Kurczak gong bao z orzeszkami', 'chinska', 'srednie'),
    ('Kurczak pieczony w całości', 'polska', 'srednie'),
    ('Kurczak po chińsku', 'chinska', 'srednie'),
    ('Kurczak tikka masala', 'indyjska', 'srednie'),
    ('Kurczak w panko', 'japonska', 'srednie'),
    ('Kurczak w sosie słodko-kwaśnym', 'chinska', 'srednie'),
    ('Kurczak w sosie sojowo czosnkowym po koreańsku', 'koreanska', 'srednie'),
    ('Kurczak z imbirem i dymką', 'chinska', 'srednie'),
    ('Kuskus z kurczakiem i warzywami', 'afrykanska', 'srednie'),
    ('Kwaśnica', 'polska', 'srednie'),
    ('Lasagne Bolognese', 'wloska', 'trudne'),
    ('Lasagne warzywna', 'wloska', 'trudne'),
    ('Leczo', 'wegierska', 'srednie'),
    ('Lo mein z wołowiną', 'chinska', 'srednie'),
    ('Lody domowe waniliowe', 'miedzynarodowa', 'srednie'),
    ('Lody z jogurtu i owoców', 'miedzynarodowa', 'latwe'),
    ('Łosoś pieczony z koperkiem', 'polska', 'latwe'),
    ('Makaron dan dan z mielonym mięsem', 'chinska', 'srednie'),
    ('Makaron jajangmyeon w sosie z czarnej fasoli', 'koreanska', 'srednie'),
    ('Makaron na zimno z pomidorkami i mozzarellą', 'wloska', 'latwe'),
    ('Makaron ramyeon z gochujangiem', 'koreanska', 'latwe'),
    ('Makaron z brokułami i czosnkiem', 'wloska', 'latwe'),
    ('Makaron z kiełbasą, cebulą i passatą', 'polska', 'latwe'),
    ('Makaron z kiełbaską i sosem pieczarkowym', 'polska', 'latwe'),
    ('Makaron z kurczakiem w sosie pomidorowym', 'wloska', 'latwe'),
    ('Makaron z kurczakiem, brokułem i sosem śmietanowym', 'miedzynarodowa', 'latwe'),
    ('Makaron z łososiem i szpinakiem', 'wloska', 'latwe'),
    ('Makaron z pesto i oliwkami', 'wloska', 'latwe'),
    ('Makaron z pesto, kurczakiem i pomidorkami', 'wloska', 'latwe'),
    ('Makaron z pomidorami, czosnkiem i parmezanem', 'wloska', 'latwe'),
    ('Makaron z serem, boczkiem i cebulką', 'polska', 'latwe'),
    ('Makaron z tuńczykiem i kaparami', 'wloska', 'latwe'),
    ('Makaron z warzywami w sosie serowym', 'miedzynarodowa', 'latwe'),
    ('Makaron zapiekany z czterema serami', 'wloska', 'srednie'),
    ('Makowiec rolowany', 'polska', 'trudne'),
    ('Mapo tofu z mielonym mięsem', 'chinska', 'srednie'),
    ('Marchewka z sezamem po koreańsku', 'koreanska', 'latwe'),
    ('Maritozzo', 'wloska', 'trudne'),
    ('Marry me chicken gnocchi', 'amerykanska', 'srednie'),
    ('Marynata gochujang do wieprzowiny', 'koreanska', 'latwe'),
    ('Marynowana kapusta pekińska po chińsku', 'chinska', 'latwe'),
    ('Marynowana rzodkiew do kimbapu', 'koreanska', 'latwe'),
    ('Marynowane grzyby po włosku', 'wloska', 'latwe'),
    ('Mazurek z masą krówkową', 'polska', 'srednie'),
    ('Migdały prażone z papryką', 'hiszpanska', 'latwe'),
    ('Minestrone', 'wloska', 'srednie'),
    ('Mini burgery', 'amerykanska', 'srednie'),
    ('Mini hot dogi', 'amerykanska', 'latwe'),
    ('Mini muffinki bananowe', 'amerykanska', 'latwe'),
    ('Mini muffinki wytrawne', 'amerykanska', 'latwe'),
    ('Mini pancakes z owocami', 'amerykanska', 'latwe'),
    ('Mini rogaliki z ciasta francuskiego i czekolady', 'francuska', 'latwe'),
    ('Mini szaszłyki z kurczaka', 'miedzynarodowa', 'latwe'),
    ('Mini tortille', 'meksykanska', 'latwe'),
    ('Mini zapiekanki z pieczarkami', 'polska', 'latwe'),
    ('Miodowe ciasteczka yakgwa', 'koreanska', 'trudne'),
    ('Mizeria', 'polska', 'latwe'),
    ('Moussaka z bakłażanem', 'grecka', 'trudne'),
    ('Mozzarella sticks', 'amerykanska', 'srednie'),
    ('Mug cake czekoladowy z mikrofali', 'amerykanska', 'latwe'),
    ('Mus czekoladowy z banana i kakao', 'miedzynarodowa', 'latwe'),
    ('Musli z jogurtem i owocami', 'miedzynarodowa', 'latwe'),
    ('Nachos z guacamole i salsą', 'meksykanska', 'latwe'),
    ('Nachosy z sosem serowym', 'meksykanska', 'latwe'),
    ('Naleśniki crêpes Suzette (pomarańczowe)*', 'francuska', 'trudne'),
    ('Naleśniki gryczane z twarogiem', 'polska', 'srednie'),
    ('Naleśniki wytrawne z serem i szynką', 'polska', 'srednie'),
    ('Naleśniki z boczkiem', 'polska', 'srednie'),
    ('Naleśniki z dżemem', 'polska', 'srednie'),
    ('Naleśniki z dżemem i bitą śmietaną', 'polska', 'srednie'),
    ('Naleśniki z mięsem zapiekane', 'polska', 'trudne'),
    ('Naleśniki z pieczarkami i serem', 'polska', 'srednie'),
    ('Naleśniki ze szpinakiem i fetą', 'polska', 'srednie'),
    ('Napój ryżowy sikhye', 'koreanska', 'trudne'),
    ('Nuggetsy domowe', 'amerykanska', 'srednie'),
    ('Ogórkowa', 'polska', 'srednie'),
    ('Oliwki nadziewane mięsem w panierce', 'wloska', 'trudne'),
    ('Omlet', 'francuska', 'latwe'),
    ('Omlet biszkoptowy z dżemem', 'polska', 'srednie'),
    ('Omlet z pieczarkami i cebulą', 'polska', 'latwe'),
    ('Omlet z serem, szynką i warzywami', 'miedzynarodowa', 'latwe'),
    ('Omlet ze szpinakiem i fetą', 'grecka', 'latwe'),
    ('Orecchiette z brokułami i anchois', 'wloska', 'srednie'),
    ('Orzeszki w miodzie i chili', 'miedzynarodowa', 'latwe'),
    ('Ossobuco z gremolatą', 'wloska', 'trudne'),
    ('Owocowa sałatka z miętą', 'miedzynarodowa', 'latwe'),
    ('Owsianka', 'miedzynarodowa', 'latwe'),
    ('Owsianka kakaowa z bananem', 'miedzynarodowa', 'latwe'),
    ('Owsianka nocna', 'miedzynarodowa', 'latwe'),
    ('Owsianka z jabłkiem i orzechami', 'miedzynarodowa', 'latwe'),
    ('Pad thai z kurczakiem', 'tajska', 'srednie'),
    ('Pajeon z dymką', 'koreanska', 'srednie'),
    ('Paluszki serowe z sezamem', 'miedzynarodowa', 'latwe'),
    ('Paluszki z ciasta francuskiego z szynką', 'francuska', 'latwe'),
    ('Pancakes amerykańskie z syropem klonowym', 'amerykanska', 'latwe'),
    ('Panettone', 'wloska', 'trudne'),
    ('Panierowana pierś kurczaka', 'polska', 'srednie'),
    ('Panini z kurczakiem, serem i sosem BBQ', 'wloska', 'latwe'),
    ('Panini z mozzarellą i pomidorem', 'wloska', 'latwe'),
    ('Panino z porchettą', 'wloska', 'latwe'),
    ('Panna cotta z owocami', 'wloska', 'srednie'),
    ('Panzanella', 'wloska', 'latwe'),
    ('Panzerotti smażone', 'wloska', 'trudne'),
    ('Pappardelle z ragù wołowym', 'wloska', 'srednie'),
    ('Parmezan z miodem i orzechami', 'wloska', 'latwe'),
    ('Parmigiana z bakłażana', 'wloska', 'trudne'),
    ('Parówki', 'polska', 'latwe'),
    ('Parówki w cieście francuskim', 'polska', 'latwe'),
    ('Passatelli w bulionie', 'wloska', 'srednie'),
    ('Pasta al forno z bakłażanem', 'wloska', 'srednie'),
    ('Pasta all''amatriciana', 'wloska', 'srednie'),
    ('Pasta alla gricia', 'wloska', 'srednie'),
    ('Pasta alla norma', 'wloska', 'srednie'),
    ('Pasta e fagioli', 'wloska', 'srednie'),
    ('Pasta jajeczna', 'polska', 'latwe'),
    ('Pasta z awokado i jajka', 'miedzynarodowa', 'latwe'),
    ('Pasta z makreli wędzonej', 'polska', 'latwe'),
    ('Pasta z pieczonego bakłażana', 'bliskowschodnia', 'latwe'),
    ('Patbingsu z kruszonym lodem', 'koreanska', 'srednie'),
    ('Pączki domowe', 'polska', 'trudne'),
    ('Penne all''arrabbiata', 'wloska', 'latwe'),
    ('Piadina roll z mortadelą', 'wloska', 'latwe'),
    ('Piadina z szynką i rukolą', 'wloska', 'latwe'),
    ('Piccata z kurczaka z cytryną', 'wloska', 'srednie'),
    ('Pieczarkowa', 'polska', 'latwe'),
    ('Pieczeń rzymska', 'polska', 'srednie'),
    ('Pieczona owsianka', 'miedzynarodowa', 'latwe'),
    ('Pieczone bataty z dipem', 'amerykanska', 'latwe'),
    ('Pieczone pieczarki z serem', 'polska', 'latwe'),
    ('Pieczone udka kurczaka', 'polska', 'latwe'),
    ('Pieczone ziemniaczki z dipem', 'polska', 'latwe'),
    ('Pierniki miodowe', 'polska', 'srednie'),
    ('Pierogi leniwe', 'polska', 'srednie'),
    ('Pierogi ruskie', 'polska', 'trudne'),
    ('Pierogi z kapustą i grzybami', 'polska', 'trudne'),
    ('Pierogi z mięsem', 'polska', 'trudne'),
    ('Pierożki dim sum na parze', 'chinska', 'trudne'),
    ('Pierożki jiaozi z wieprzowiną', 'chinska', 'trudne'),
    ('Pierożki mandu z warzywami', 'koreanska', 'trudne'),
    ('Pizza bianca z rozmarynem', 'wloska', 'trudne'),
    ('Pizza domowa', 'wloska', 'trudne'),
    ('Pizza margherita', 'wloska', 'trudne'),
    ('Pizza na tortilli', 'wloska', 'latwe'),
    ('Pizzerinki', 'wloska', 'latwe'),
    ('Placek po węgiersku', 'wegierska', 'trudne'),
    ('Placek z rabarbarem i bezą', 'polska', 'srednie'),
    ('Placki bananowe z „chrupką”', 'miedzynarodowa', 'latwe'),
    ('Placki bananowe z jogurtem i owocami', 'miedzynarodowa', 'latwe'),
    ('Placki owsiane z jogurtem', 'miedzynarodowa', 'latwe'),
    ('Placki z cukinii po koreańsku', 'koreanska', 'srednie'),
    ('Placki z cukinii z sosem jogurtowym', 'miedzynarodowa', 'srednie'),
    ('Placki z dymką po chińsku', 'chinska', 'srednie'),
    ('Placki z kaszy jaglanej', 'polska', 'srednie'),
    ('Placki ziemniaczane mini', 'polska', 'srednie'),
    ('Placki ziemniaczane z sosem czosnkowym', 'polska', 'srednie'),
    ('Placki ziemniaczane ze śmietaną', 'polska', 'srednie'),
    ('Placuszki twarogowe', 'polska', 'latwe'),
    ('Placuszki z cukinii po włosku', 'wloska', 'srednie'),
    ('Płatki z mlekiem', 'miedzynarodowa', 'latwe'),
    ('Podudzia w marynacie ziołowej', 'polska', 'latwe'),
    ('Polenta z gorgonzolą', 'wloska', 'srednie'),
    ('Polędwiczka wieprzowa z kurkami', 'polska', 'srednie'),
    ('Pollo alla cacciatora', 'wloska', 'srednie'),
    ('Pomidorki faszerowane ricottą', 'wloska', 'latwe'),
    ('Pomidorówka', 'polska', 'latwe'),
    ('Popcorn karmelowy', 'amerykanska', 'latwe'),
    ('Prażona kukurydza z masłem', 'amerykanska', 'latwe'),
    ('Prażone pestki dyni z solą', 'miedzynarodowa', 'latwe'),
    ('Prosciutto z melonem', 'wloska', 'latwe'),
    ('Pstrąg pieczony z masłem czosnkowym', 'polska', 'srednie'),
    ('Ptasie mleczko domowe', 'polska', 'trudne'),
    ('Pulpety w sosie koperkowym', 'polska', 'srednie'),
    ('Pyzy/kluski śląskie', 'polska', 'srednie'),
    ('Quesadilla z serem i fasolą', 'meksykanska', 'latwe'),
    ('Quesadilla z serem i kurczakiem', 'meksykanska', 'latwe'),
    ('Quesadilla z szarpaną wieprzowiną', 'meksykanska', 'srednie'),
    ('Racuchy z jabłkami', 'polska', 'srednie'),
    ('Ravioli z ricottą i szpinakiem', 'wloska', 'trudne'),
    ('Ribollita', 'wloska', 'srednie'),
    ('Ricotta z miodem i orzechami na grzance', 'wloska', 'latwe'),
    ('Rigatoni alla genovese', 'wloska', 'srednie'),
    ('Risotto alla milanese', 'wloska', 'srednie'),
    ('Risotto z dynią i szałwią', 'wloska', 'srednie'),
    ('Risotto z grzybami leśnymi', 'wloska', 'srednie'),
    ('Risotto z owocami morza', 'wloska', 'trudne'),
    ('Risotto z warzywami', 'wloska', 'srednie'),
    ('Rogaliki z marmoladą', 'polska', 'srednie'),
    ('Rolada biszkoptowa z dżemem', 'polska', 'trudne'),
    ('Roladki drobiowe ze szpinakiem', 'polska', 'srednie'),
    ('Roladki z bakłażana z ricottą', 'wloska', 'srednie'),
    ('Roladki z cukinii z serkiem', 'wloska', 'latwe'),
    ('Roladki z szynki i serka', 'polska', 'latwe'),
    ('Roladki z tortilli ze szpinakiem', 'miedzynarodowa', 'latwe'),
    ('Rolowany omlet koreański z warzywami', 'koreanska', 'srednie'),
    ('Rosół', 'polska', 'srednie'),
    ('Rosół samgyetang z kurczakiem i żeń-szeniem', 'koreanska', 'trudne'),
    ('Ryba po grecku', 'polska', 'srednie'),
    ('Ryba w sosie musztardowym', 'polska', 'srednie'),
    ('Ryż jaśminowy na parze', 'chinska', 'latwe'),
    ('Ryż na mleku z cynamonem i jabłkiem', 'polska', 'latwe'),
    ('Ryż smażony po kantońsku', 'chinska', 'srednie'),
    ('Ryż smażony z jajkiem, kurczakiem i warzywami', 'chinska', 'latwe'),
    ('Ryż smażony z krewetkami', 'chinska', 'latwe'),
    ('Ryż z jajkiem i masłem po koreańsku', 'koreanska', 'latwe'),
    ('Ryż z warzywami stir-fry', 'chinska', 'latwe'),
    ('Ryż z warzywami w sosie curry', 'indyjska', 'latwe'),
    ('Saltimbocca alla romana', 'wloska', 'srednie'),
    ('Sałatka caprese', 'wloska', 'latwe'),
    ('Sałatka cezar z kurczakiem', 'amerykanska', 'srednie'),
    ('Sałatka grecka z fetą', 'grecka', 'latwe'),
    ('Sałatka gyros', 'grecka', 'srednie'),
    ('Sałatka jarzynowa', 'polska', 'srednie'),
    ('Sałatka makaronowa z kurczakiem i kukurydzą', 'miedzynarodowa', 'latwe'),
    ('Sałatka nicejska', 'francuska', 'latwe'),
    ('Sałatka ryżowa po włosku', 'wloska', 'latwe'),
    ('Sałatka z arbuzem i fetą', 'grecka', 'latwe'),
    ('Sałatka z awokado i pomidorkami', 'miedzynarodowa', 'latwe'),
    ('Sałatka z bobem, pecorino i miętą', 'wloska', 'latwe'),
    ('Sałatka z burakiem, kozim serem i orzechami', 'francuska', 'latwe'),
    ('Sałatka z cukinii grillowanej z miętą', 'wloska', 'latwe'),
    ('Sałatka z fasolą i tuńczykiem', 'wloska', 'latwe'),
    ('Sałatka z gruszką, gorgonzolą i orzechami', 'wloska', 'latwe'),
    ('Sałatka z jajkiem, bekonem i grzankami', 'miedzynarodowa', 'latwe'),
    ('Sałatka z kapusty pekińskiej i kukurydzy', 'polska', 'latwe'),
    ('Sałatka z karczochami marynowanymi', 'wloska', 'latwe'),
    ('Sałatka z kaszą gryczaną i pieczonymi warzywami', 'polska', 'latwe'),
    ('Sałatka z komosą ryżową i warzywami', 'miedzynarodowa', 'latwe'),
    ('Sałatka z kopru włoskiego z oliwą', 'wloska', 'latwe'),
    ('Sałatka z kukurydzy, papryki i fasoli', 'meksykanska', 'latwe'),
    ('Sałatka z kurczakiem curry', 'indyjska', 'latwe'),
    ('Sałatka z kurczakiem, fetą i grzankami', 'grecka', 'latwe'),
    ('Sałatka z makaronem szklanym', 'chinska', 'latwe'),
    ('Sałatka z ogórka i pomidora ze śmietaną', 'polska', 'latwe'),
    ('Sałatka z ogórka po syczuańsku', 'chinska', 'latwe'),
    ('Sałatka z ogórka w sosie gochujang', 'koreanska', 'latwe'),
    ('Sałatka z papryki i cebuli marynowanej', 'polska', 'latwe'),
    ('Sałatka z pieczoną dynią i fetą', 'grecka', 'latwe'),
    ('Sałatka z pieczonym kurczakiem i awokado', 'miedzynarodowa', 'latwe'),
    ('Sałatka z pomidorami suszonymi i kaparami', 'wloska', 'latwe'),
    ('Sałatka z pomidorów i cebuli', 'polska', 'latwe'),
    ('Sałatka z radicchio i orzechami', 'wloska', 'latwe'),
    ('Sałatka z roszponki i gruszki', 'francuska', 'latwe'),
    ('Sałatka z rukoli, pomidorków i parmezanu', 'wloska', 'latwe'),
    ('Sałatka z selera naciowego i orzechów włoskich', 'miedzynarodowa', 'latwe'),
    ('Sałatka z soczewicą i pieczonym batatem', 'miedzynarodowa', 'latwe'),
    ('Sałatka z tortellini i pesto', 'wloska', 'latwe'),
    ('Sałatka z tuńczykiem i jajkiem', 'miedzynarodowa', 'latwe'),
    ('Sałatka zielona', 'miedzynarodowa', 'latwe'),
    ('Scaloppine z pieczarkami', 'wloska', 'srednie'),
    ('Schab ze śliwką', 'polska', 'srednie'),
    ('Semifreddo pistacjowe', 'wloska', 'srednie'),
    ('Ser halloumi z patelni', 'grecka', 'latwe'),
    ('Serek waniliowy z owocami i granolą', 'miedzynarodowa', 'latwe'),
    ('Serek wiejski z pomidorem i bazylią', 'miedzynarodowa', 'latwe'),
    ('Sernik na zimno', 'polska', 'srednie'),
    ('Sernik pieczony z rodzynkami', 'polska', 'trudne'),
    ('Shakshuka z jajkami i pomidorami', 'bliskowschodnia', 'srednie'),
    ('Skrzydełka BBQ', 'amerykanska', 'srednie'),
    ('Skrzydełka w glazurze gochujang', 'koreanska', 'srednie'),
    ('Skrzydełka w sosie sojowo miodowym', 'chinska', 'srednie'),
    ('Słupki warzywne z hummusem', 'bliskowschodnia', 'latwe'),
    ('Smażone banany w cieście', 'chinska', 'srednie'),
    ('Smażony ryż z kimchi i gochujangiem', 'koreanska', 'latwe'),
    ('Smoothie bowl z owocami i granolą', 'amerykanska', 'latwe'),
    ('Smoothie zielone ze szpinakiem i bananem', 'amerykanska', 'latwe'),
    ('Sorbet truskawkowy', 'wloska', 'latwe'),
    ('Sos słodko kwaśny domowy', 'chinska', 'latwe'),
    ('Sos ssamjang do mięsa', 'koreanska', 'latwe'),
    ('Spaghetti Aglio e Olio', 'wloska', 'latwe'),
    ('Spaghetti alla puttanesca', 'wloska', 'srednie'),
    ('Spaghetti bolognese', 'wloska', 'srednie'),
    ('Spaghetti cacio e pepe', 'wloska', 'srednie'),
    ('Spaghetti carbonara', 'wloska', 'srednie'),
    ('Spring rolls (sajgonki)', 'wietnamska', 'trudne'),
    ('Stek wołowy', 'amerykanska', 'srednie'),
    ('Stek z kalafiora', 'miedzynarodowa', 'latwe'),
    ('Stir-fry z wołowiną', 'chinska', 'srednie'),
    ('Stracciatella alla romana', 'wloska', 'latwe'),
    ('Sundubu jjigae z miękkim tofu', 'koreanska', 'srednie'),
    ('Surówka z białej kapusty i ananasa', 'polska', 'latwe'),
    ('Surówka z brokułów z rodzynkami', 'polska', 'latwe'),
    ('Surówka z buraka i chrzanu', 'polska', 'latwe'),
    ('Surówka z cukinii i marchewki', 'polska', 'latwe'),
    ('Surówka z czerwonej kapusty', 'polska', 'latwe'),
    ('Surówka z dyni i jabłka', 'polska', 'latwe'),
    ('Surówka z fenkuła i pomarańczy', 'wloska', 'latwe'),
    ('Surówka z jarmużu i jabłka', 'polska', 'latwe'),
    ('Surówka z kalafiora na surowo', 'polska', 'latwe'),
    ('Surówka z kalarepy', 'polska', 'latwe'),
    ('Surówka z kiszonej kapusty', 'polska', 'latwe'),
    ('Surówka z ogórka kiszonego i cebuli', 'polska', 'latwe'),
    ('Surówka z pora i jabłka', 'polska', 'latwe'),
    ('Surówka z rzepy i marchewki', 'polska', 'latwe'),
    ('Surówka z rzodkiewki i szczypiorku', 'polska', 'latwe'),
    ('Surówka z selera i jabłka', 'polska', 'latwe'),
    ('Sushi bez zawijania', 'japonska', 'srednie'),
    ('Szarlotka', 'polska', 'srednie'),
    ('Szaszłyki caprese na patyczkach', 'wloska', 'latwe'),
    ('Szaszłyki z kurczaka i warzyw', 'polska', 'srednie'),
    ('Szczawiowa z jajkiem', 'polska', 'srednie'),
    ('Sznycel wiedeński', 'niemiecka', 'srednie'),
    ('Szpinak z sezamem po koreańsku', 'koreanska', 'latwe'),
    ('Szybkie leczo z kiełbasą i papryką', 'wegierska', 'latwe'),
    ('Śliwki w boczku', 'polska', 'latwe'),
    ('Tacos z mięsem mielonym i warzywami', 'meksykanska', 'srednie'),
    ('Tagliatelle z boczniakami', 'wloska', 'srednie'),
    ('Tagliatelle z polędwicą wołową', 'wloska', 'srednie'),
    ('Tapenada z oliwek', 'francuska', 'latwe'),
    ('Taralli', 'wloska', 'srednie'),
    ('Tarta warzywna', 'francuska', 'srednie'),
    ('Tarta ze szpinakiem i ricottą', 'wloska', 'srednie'),
    ('Tartinki z serkiem i łososiem', 'francuska', 'latwe'),
    ('Tiramisu', 'wloska', 'srednie'),
    ('Tofu duszone w sosie sojowym po koreańsku', 'koreanska', 'latwe'),
    ('Tofu smażone w sosie gochujang', 'koreanska', 'latwe'),
    ('Tofu smażone z warzywami po chińsku', 'chinska', 'latwe'),
    ('Tofu w sosie teriyaki', 'japonska', 'latwe'),
    ('Tom kha z kurczakiem', 'tajska', 'srednie'),
    ('Torta caprese', 'wloska', 'srednie'),
    ('Torta della nonna', 'wloska', 'trudne'),
    ('Tortellini w bulionie', 'wloska', 'srednie'),
    ('Tortilla kebab', 'turecka', 'srednie'),
    ('Tortilla śniadaniowa z jajecznicą', 'meksykanska', 'latwe'),
    ('Tortilla z kurczakiem, warzywami i sosem czosnkowym', 'meksykanska', 'latwe'),
    ('Tortilla z serem, jajkiem i szynką', 'meksykanska', 'latwe'),
    ('Tortilla zapiekana z tuńczykiem', 'meksykanska', 'latwe'),
    ('Tosty francuskie na słodko', 'francuska', 'latwe'),
    ('Tosty francuskie na słono', 'francuska', 'latwe'),
    ('Tosty koreańskie z jajkiem i kapustą', 'koreanska', 'latwe'),
    ('Tosty z serem i szynką', 'polska', 'latwe'),
    ('Tramezzini z tuńczykiem', 'wloska', 'latwe'),
    ('Trofie z pesto i ziemniakami', 'wloska', 'srednie'),
    ('Tteokbokki z owocami morza', 'koreanska', 'srednie'),
    ('Tteokbokki z serem', 'koreanska', 'latwe'),
    ('Twarożek z rzodkiewką i szczypiorkiem', 'polska', 'latwe'),
    ('Vitello tonnato', 'wloska', 'trudne'),
    ('Wątróbka drobiowa z cebulą', 'polska', 'latwe'),
    ('Wieprzowina gu lao rou', 'chinska', 'trudne'),
    ('Wieprzowina w sosie gochujang', 'koreanska', 'srednie'),
    ('Włoski omlet z pomidorami i bazylią', 'wloska', 'latwe'),
    ('Wołowina w sosie ostrygowym', 'chinska', 'srednie'),
    ('Wołowina z brokułami po chińsku', 'chinska', 'srednie'),
    ('Wrap z falafelem i hummusem', 'bliskowschodnia', 'srednie'),
    ('Wrap z jajkiem, bekonem i sałatą', 'amerykanska', 'latwe'),
    ('Wrap z kurczakiem i warzywami', 'miedzynarodowa', 'latwe'),
    ('Wrap z mięsem mielonym, serem i warzywami', 'miedzynarodowa', 'latwe'),
    ('Zabaglione', 'wloska', 'srednie'),
    ('Zalewajka', 'polska', 'srednie'),
    ('Zapiekane bagietki z serem, pieczarkami i szynką', 'polska', 'latwe'),
    ('Zapiekane jajka z warzywami', 'miedzynarodowa', 'latwe'),
    ('Zapiekane papryki z ryżem i ziołami', 'miedzynarodowa', 'srednie'),
    ('Zapiekane ziemniaki z serem pleśniowym', 'francuska', 'srednie'),
    ('Zapiekanka makaronowa z kurczakiem', 'polska', 'srednie'),
    ('Zapiekanka z bakłażana z serem', 'wloska', 'srednie'),
    ('Zapiekanka z brokułami i kurczakiem', 'polska', 'srednie'),
    ('Zapiekanka z kalafiora', 'polska', 'srednie'),
    ('Zapiekanka ziemniaczana z mięsem mielonym', 'polska', 'srednie'),
    ('Zapiekanki', 'polska', 'latwe'),
    ('Ziemniaki duszone w sosie sojowym', 'koreanska', 'latwe'),
    ('Zimny makaron bibim guksu', 'koreanska', 'srednie'),
    ('Zimny makaron naengmyeon w bulionie', 'koreanska', 'trudne'),
    ('Zrazy wołowe zawijane', 'polska', 'trudne'),
    ('Zupa cukiniowa z serkiem topionym', 'polska', 'latwe'),
    ('Zupa cytrynowa', 'polska', 'srednie'),
    ('Zupa dyniowa z imbirem', 'miedzynarodowa', 'latwe'),
    ('Zupa fasolowa', 'polska', 'srednie'),
    ('Zupa grzybowa', 'polska', 'srednie'),
    ('Zupa kalarepowa', 'polska', 'latwe'),
    ('Zupa koperkowa', 'polska', 'latwe'),
    ('Zupa krem z batatów', 'miedzynarodowa', 'latwe'),
    ('Zupa krem z brokułem i cukinią', 'miedzynarodowa', 'latwe'),
    ('Zupa krem z pomidorów z grzankami', 'polska', 'latwe'),
    ('Zupa kukurydziana z kurczakiem', 'chinska', 'latwe'),
    ('Zupa marchewkowo-imbirowa', 'miedzynarodowa', 'latwe'),
    ('Zupa miso z tofu', 'japonska', 'latwe'),
    ('Zupa neapolitańska', 'wloska', 'latwe'),
    ('Zupa owocowa z makaronem', 'polska', 'latwe'),
    ('Zupa porowa z ziemniakami', 'polska', 'latwe'),
    ('Zupa ramen z kurczakiem', 'japonska', 'srednie'),
    ('Zupa rybna', 'polska', 'srednie'),
    ('Zupa selerowa z grzankami', 'polska', 'latwe'),
    ('Zupa tteokguk z plackami ryżowymi', 'koreanska', 'srednie'),
    ('Zupa wonton z pierożkami', 'chinska', 'trudne'),
    ('Zupa z ciecierzycy i pomidorów', 'bliskowschodnia', 'latwe'),
    ('Zupa z kiełków sojowych po koreańsku', 'koreanska', 'latwe'),
    ('Zupa z makaronem i wołowiną po chińsku', 'chinska', 'srednie'),
    ('Zupa z orkiszem i warzywami', 'polska', 'latwe'),
    ('Zupa z soczewicy czerwonej', 'bliskowschodnia', 'latwe'),
    ('Zupa ziemniaczana z boczkiem', 'polska', 'latwe'),
    ('Zuppa toscana z jarmużem i kiełbasą', 'wloska', 'srednie'),
    ('Żeberka pieczone w miodzie i musztardzie', 'polska', 'srednie'),
    ('Żeberka w sosie hoisin', 'chinska', 'srednie'),
    ('Żur', 'polska', 'srednie')
)
update dania d
set kuchnia = coalesce(d.kuchnia, p.kuchnia),
    poziom  = coalesce(d.poziom,  p.poziom)
from przypisania p
where btrim(d."Danie") = p.danie
  and (d.kuchnia is null or d.poziom is null);

-- ── Sprawdzenie po wykonaniu ──
-- Powinno pokazać 0 w obu kolumnach „bez_...".
--
-- select
--   count(distinct "Danie")                                as dan_razem,
--   count(distinct "Danie") filter (where kuchnia is null)  as bez_kuchni,
--   count(distinct "Danie") filter (where poziom is null)   as bez_poziomu
-- from dania;

-- ── Rozkład krajów ──
-- select kuchnia, count(distinct "Danie") as ile
-- from dania group by kuchnia order by ile desc;
